# Generated by Django 5.1.4 on 2024-12-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='attachment',
            new_name='attachment_code',
        ),
    ]
